# Generated by Django 4.1.5 on 2023-01-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_member_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='name',
            new_name='event',
        ),
    ]
