# Generated by Django 4.1.5 on 2023-01-19 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_name_events_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='end',
        ),
        migrations.RemoveField(
            model_name='events',
            name='start',
        ),
    ]
