# Generated by Django 4.1.5 on 2023-01-31 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_events_end_remove_events_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='member',
            name='event',
        ),
        migrations.AddField(
            model_name='member',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.events'),
        ),
    ]
