# Generated by Django 4.1.5 on 2023-02-01 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_events_event_alter_events_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='event',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
